import Head from "next/head"
import { Cormorant_Garamond, DM_Sans } from "next/font/google"
import { PackageDescriptionSection } from "@/sections/PackageDescriptionSection"

export const cormorant = Cormorant_Garamond({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-cormorant",
    display: "swap",
})

export const dmSans = DM_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-dm-sans",
    display: "swap",
})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${dmSans.variable} ${cormorant.variable}`}>
                <div
                    style={{
                        fontFamily: "var(--font-dm-sans)",
                    }}
                >
                    <PackageDescriptionSection />
                </div>
            </div>
        </>
    )
}
